const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Camera3D,
		C3.Plugins.Shape3D,
		C3.Plugins.Sprite,
		C3.Plugins.Keyboard,
		C3.Plugins.TiledBg,
		C3.Behaviors.Sin,
		C3.Plugins.NinePatch,
		C3.Behaviors.Tween,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Flash,
		C3.Plugins.Touch,
		C3.Plugins.Mikal_3DObject,
		C3.Behaviors.mikal_rotate_shape,
		C3.Plugins.Audio,
		C3.Behaviors.Pin,
		C3.Behaviors.Anchor,
		C3.Behaviors.Fade,
		C3.Behaviors.lunarray_LiteTween,
		C3.Plugins.ValerypopoffJSPlugin,
		C3.Plugins.Browser,
		C3.Plugins.Text,
		C3.Plugins.Multiplayer,
		C3.Plugins.Arr,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.SetZElevation,
		C3.Plugins.TiledBg.Exps.ZElevation,
		C3.Plugins.TiledBg.Acts.AddChild,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Shape3D.Exps.Width,
		C3.Plugins.Shape3D.Exps.Height,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Shape3D.Exps.LayerName,
		C3.Plugins.Shape3D.Exps.BBoxLeft,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Shape3D.Exps.BBoxTop,
		C3.Plugins.Shape3D.Acts.SetZElevation,
		C3.Plugins.Shape3D.Exps.ZElevation,
		C3.Plugins.Shape3D.Exps.ZHeight,
		C3.Plugins.Shape3D.Exps.X,
		C3.Plugins.Shape3D.Exps.Y,
		C3.Plugins.Shape3D.Acts.SetFaceObject,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.Spritefont2.Acts.SetBoolInstanceVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Acts.SetZElevation,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Shape3D.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Mikal_3DObject.Acts.Destroy,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Exps.ZElevation,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Shape3D.Acts.SetAngle,
		C3.Plugins.Shape3D.Acts.AddChild,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.Camera3D.Acts.LookAtPosition,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Mikal_3DObject.Cnds.IsLoaded,
		C3.Plugins.Mikal_3DObject.Acts.PlayAnimation,
		C3.Plugins.Mikal_3DObject.Acts.SetAnimationRate,
		C3.Plugins.Mikal_3DObject.Acts.SetAnimationSpeed,
		C3.Plugins.Mikal_3DObject.Acts.SetRotationOrdered,
		C3.Plugins.Mikal_3DObject.Exps.ZAngle,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Mikal_3DObject.Acts.SetPos,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Mikal_3DObject.Cnds.IsPlaying,
		C3.Plugins.Mikal_3DObject.Acts.SetDefaultColor,
		C3.Plugins.Shape3D.Acts.SetPos,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Behaviors.lunarray_LiteTween.Acts.Start,
		C3.Plugins.ValerypopoffJSPlugin.Acts.ExecuteJSWithParamsNonvar,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Mikal_3DObject.Exps.XAngle,
		C3.Plugins.Mikal_3DObject.Exps.YAngle,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Mikal_3DObject.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Mikal_3DObject.Acts.SetInstanceVar,
		C3.Plugins.Mikal_3DObject.Cnds.OnLoaded,
		C3.Plugins.Mikal_3DObject.Exps.X,
		C3.Plugins.Mikal_3DObject.Exps.Y,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Multiplayer.Acts.SignallingDisconnect,
		C3.Plugins.Multiplayer.Acts.SetBandwidthProfile,
		C3.Plugins.Multiplayer.Acts.SyncObject2,
		C3.Plugins.Multiplayer.Acts.SyncObjectInstanceVar,
		C3.Plugins.Multiplayer.Acts.SignallingConnect,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.Arr.Acts.Pop,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Text.Acts.AppendText,
		C3.Plugins.Arr.Exps.CurValue,
		C3.Plugins.Multiplayer.Cnds.OnSignallingConnected,
		C3.Plugins.Multiplayer.Acts.SignallingLogin,
		C3.Plugins.Multiplayer.Cnds.OnSignallingLoggedIn,
		C3.Plugins.Multiplayer.Exps.MyAlias,
		C3.Plugins.Multiplayer.Exps.MyID,
		C3.Plugins.Multiplayer.Acts.SignallingAutoJoinRoom,
		C3.Plugins.Multiplayer.Cnds.OnSignallingDisconnected,
		C3.Plugins.Multiplayer.Cnds.OnSignallingError,
		C3.Plugins.Multiplayer.Exps.ErrorMessage,
		C3.Plugins.Multiplayer.Cnds.OnSignallingLeftRoom,
		C3.Plugins.Multiplayer.Cnds.OnSignallingKicked,
		C3.Plugins.Multiplayer.Exps.StatInboundCount,
		C3.Plugins.Multiplayer.Exps.StatInboundBandwidth,
		C3.Plugins.Multiplayer.Exps.StatOutboundCount,
		C3.Plugins.Multiplayer.Exps.StatOutboundBandwidth,
		C3.Plugins.Multiplayer.Exps.PeerLatency,
		C3.Plugins.Multiplayer.Exps.HostID,
		C3.Plugins.Multiplayer.Exps.PeerPDV,
		C3.Plugins.Multiplayer.Cnds.OnPeerMessage,
		C3.Plugins.Multiplayer.Exps.Message,
		C3.Plugins.Multiplayer.Cnds.OnPeerConnected,
		C3.Plugins.Multiplayer.Acts.HostBroadcastMessage,
		C3.Plugins.Multiplayer.Exps.PeerAlias,
		C3.Plugins.Mikal_3DObject.Acts.SetVisible,
		C3.Plugins.Shape3D.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Multiplayer.Cnds.OnSignallingJoinedRoom,
		C3.Plugins.Multiplayer.Cnds.IsHost,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Multiplayer.Acts.AssociateObjectWithPeer,
		C3.Plugins.Mikal_3DObject.Exps.ZElevation,
		C3.Plugins.Mikal_3DObject.Cnds.CompareX,
		C3.Plugins.Multiplayer.Acts.SendPeerMessage,
		C3.Plugins.Mikal_3DObject.Acts.AddInstanceVar,
		C3.Plugins.Mikal_3DObject.Cnds.CompareY,
		C3.Plugins.Mikal_3DObject.Acts.SetY,
		C3.Plugins.Mikal_3DObject.Acts.SetX,
		C3.Plugins.Multiplayer.Acts.SignallingLeaveRoom,
		C3.Plugins.Multiplayer.Acts.DisconnectRoom,
		C3.Plugins.System.Acts.SubVar
	];
};
self.C3_JsPropNameTable = [
	{"3DCamera": 0},
	{CoveredInGrass: 0},
	{SolidModel: 0},
	{peer: 0},
	{PlayerCollider: 0},
	{Keyboard: 0},
	{peerid: 0},
	{PlayerModel: 0},
	{PlayerShadow: 0},
	{SandTopTexture: 0},
	{Sine: 0},
	{WaterTexture: 0},
	{PlayerTextures: 0},
	{GrassTopTexture: 0},
	{GrassSideTexture: 0},
	{SandSideTexture: 0},
	{Tween: 0},
	{Foam: 0},
	{PalmTree: 0},
	{BadGameOver: 0},
	{EndTriggerZone: 0},
	{WaterSplashModel: 0},
	{WaterSplashTextures: 0},
	{SandPalmTreeTexture: 0},
	{GrassPalmTreeTexture: 0},
	{DecorationModel: 0},
	{WoodLogTextureLeft: 0},
	{WoodLogTextureRight: 0},
	{WoodLogTextureTop: 0},
	{WoodLogTextureBottom: 0},
	{WoodLogTextureFront: 0},
	{DecorationTextures: 0},
	{TentModelLeft: 0},
	{TentModelRight: 0},
	{RaftBaseModel: 0},
	{RaftPoleModel: 0},
	{RaftClothModel: 0},
	{FlagPoleModel: 0},
	{FlagModel: 0},
	{IsAlive: 0},
	{TutorialText: 0},
	{Flash: 0},
	{VictoryText: 0},
	{Touch: 0},
	{Sprite13: 0},
	{SandTopTexture2: 0},
	{"3DObject2": 0},
	{Rotate3D: 0},
	{"3DObject": 0},
	{"3DObject3": 0},
	{Audio: 0},
	{"3DObject4": 0},
	{"3DObject5": 0},
	{inputs: 0},
	{anim: 0},
	{sidemove: 0},
	{angle: 0},
	{dead: 0},
	{win: 0},
	{Pin: 0},
	{GamePlayer: 0},
	{Anchor: 0},
	{GameScoreFont: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{gameplayers: 0},
	{Soundsprite: 0},
	{restartbtn: 0},
	{Sprite2sp: 0},
	{PlayerColliderBot1: 0},
	{Run: 0},
	{Runposition: 0},
	{vulnerablechoose: 0},
	{killhim: 0},
	{BotPlayer1: 0},
	{Fade: 0},
	{Sprite5: 0},
	{Counter: 0},
	{Blood: 0},
	{Bloodmodel: 0},
	{PlayerModel2: 0},
	{"3DShape": 0},
	{Playerarrow: 0},
	{arrow: 0},
	{Sprite6: 0},
	{gameroundfont: 0},
	{light: 0},
	{LiteTween: 0},
	{gameover: 0},
	{RESTART: 0},
	{MENU: 0},
	{gameoverscore: 0},
	{ValerypopoffJS: 0},
	{Browser: 0},
	{Roundcompleted: 0},
	{Roundcompleted2: 0},
	{Winscore: 0},
	{MENU2: 0},
	{botshadow1: 0},
	{PlayerColliderBot2: 0},
	{animmp: 0},
	{deadmp: 0},
	{winmp: 0},
	{BotPlayer2: 0},
	{botshadow2: 0},
	{PlayerColliderBot3: 0},
	{BotPlayer3: 0},
	{botshadow3: 0},
	{PlayerColliderBot4: 0},
	{BotPlayer4: 0},
	{botshadow4: 0},
	{PlayerColliderBot5: 0},
	{BotPlayer5: 0},
	{botshadow5: 0},
	{PlayerColliderBot6: 0},
	{BotPlayer6: 0},
	{botshadow6: 0},
	{PlayerColliderBot7: 0},
	{BotPlayer7: 0},
	{botshadow7: 0},
	{PlayerColliderBot8: 0},
	{BotPlayer8: 0},
	{botshadow8: 0},
	{PlayerColliderBot9: 0},
	{BotPlayer9: 0},
	{botshadow9: 0},
	{Bot1arrow: 0},
	{botnumber1: 0},
	{botnumber2: 0},
	{Bot1arrow2: 0},
	{botnumber3: 0},
	{Bot1arrow3: 0},
	{botnumber4: 0},
	{Bot1arrow4: 0},
	{botnumber5: 0},
	{Bot1arrow5: 0},
	{botnumber6: 0},
	{Bot1arrow6: 0},
	{botnumber7: 0},
	{Bot1arrow7: 0},
	{botnumber8: 0},
	{Bot1arrow8: 0},
	{botnumber9: 0},
	{Bot1arrow9: 0},
	{enemyshadow: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Youwin: 0},
	{ScoreDisplay: 0},
	{Multiplayer: 0},
	{PlayerCollider2: 0},
	{LogText: 0},
	{LogMessages: 0},
	{NetStats: 0},
	{tracker: 0},
	{lightstate: 0},
	{dollstate: 0},
	{Sprite11: 0},
	{movement: 0},
	{score: 0},
	{GamePlayer2: 0},
	{PlayerShadow2: 0},
	{Sprite12: 0},
	{Timer: 0},
	{p1: 0},
	{p2: 0},
	{p3: 0},
	{p4: 0},
	{DECORATIONSPAWNRATE: 0},
	{FLOWERSPAWNRATE: 0},
	{RandomNumber: 0},
	{WATERBASEZELEVATION: 0},
	{WATERXYMOVEMENTSTRENGTH: 0},
	{WATERMOVEMENTZSTRENGTH: 0},
	{WATERMOVEMENTSPEED: 0},
	{WaterAngleXMovement: 0},
	{WaterAngleYMovement: 0},
	{WaterAngleZMovement: 0},
	{StartingTouch: 0},
	{rotatevariable: 0},
	{Trigger: 0},
	{GameReady: 0},
	{Vulnerable: 0},
	{Dollready: 0},
	{GameRound: 0},
	{GameOver: 0},
	{Coins: 0},
	{Sonido: 0},
	{Playerscount: 0},
	{deadplayers: 0},
	{Botstate1: 0},
	{Botstate2: 0},
	{Botstate3: 0},
	{Botstate4: 0},
	{Botstate5: 0},
	{Botstate6: 0},
	{Botstate7: 0},
	{Botstate8: 0},
	{Botstate9: 0},
	{PLAYERACCELERATION: 0},
	{PLAYERDECELERATION: 0},
	{PLAYERMAXSPEED: 0},
	{PLAYERJUMPSTRENGTH: 0},
	{PLAYERGRAVITYSTRENGTH: 0},
	{WalkLeft: 0},
	{WalkRight: 0},
	{WalkUp: 0},
	{WalkDown: 0},
	{Score: 0},
	{InputHorizontalAxis: 0},
	{InputVerticalAxis: 0},
	{MovementVectorX: 0},
	{MovementVectorY: 0},
	{LAYOUTMARGIN: 0},
	{PressedJump: 0},
	{MovementVectorZ: 0},
	{PLAYERMINZELEVATION: 0},
	{HighestSolidZElevation: 0},
	{AngleOfMotion: 0},
	{MOVEMENTTHRESHOLD: 0},
	{PreviousZElevation: 0},
	{ValueDirection: 0},
	{CurrentValue: 0},
	{TargetValue: 0},
	{Speed: 0},
	{MyUsername: 0},
	{message: 0},
	{state: 0},
	{GAME_NAME: 0},
	{INSTANCE_NAME: 0},
	{ROOM_NAME: 0},
	{GameState: 0},
	{clientetouchend: 0},
	{creatorpeerx: 0}
];

self.InstanceType = {
	_3DCamera: class extends self.IInstance {},
	SolidModel: class extends self.I3DShapeInstance {},
	PlayerCollider: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	PlayerModel: class extends self.I3DShapeInstance {},
	PlayerShadow: class extends self.ISpriteInstance {},
	SandTopTexture: class extends self.ITiledBackgroundInstance {},
	WaterTexture: class extends self.ITiledBackgroundInstance {},
	PlayerTextures: class extends self.ISpriteInstance {},
	GrassTopTexture: class extends self.ITiledBackgroundInstance {},
	GrassSideTexture: class extends self.IWorldInstance {},
	SandSideTexture: class extends self.IWorldInstance {},
	Foam: class extends self.ISpriteInstance {},
	PalmTree: class extends self.I3DShapeInstance {},
	EndTriggerZone: class extends self.ISpriteInstance {},
	WaterSplashModel: class extends self.I3DShapeInstance {},
	WaterSplashTextures: class extends self.ISpriteInstance {},
	SandPalmTreeTexture: class extends self.ISpriteInstance {},
	GrassPalmTreeTexture: class extends self.ISpriteInstance {},
	DecorationModel: class extends self.I3DShapeInstance {},
	WoodLogTextureLeft: class extends self.ISpriteInstance {},
	WoodLogTextureRight: class extends self.ISpriteInstance {},
	WoodLogTextureTop: class extends self.ISpriteInstance {},
	WoodLogTextureBottom: class extends self.ISpriteInstance {},
	WoodLogTextureFront: class extends self.ISpriteInstance {},
	DecorationTextures: class extends self.ISpriteInstance {},
	TentModelLeft: class extends self.I3DShapeInstance {},
	TentModelRight: class extends self.I3DShapeInstance {},
	RaftBaseModel: class extends self.I3DShapeInstance {},
	RaftPoleModel: class extends self.I3DShapeInstance {},
	RaftClothModel: class extends self.I3DShapeInstance {},
	FlagPoleModel: class extends self.I3DShapeInstance {},
	FlagModel: class extends self.I3DShapeInstance {},
	TutorialText: class extends self.ISpriteFontInstance {},
	VictoryText: class extends self.ISpriteFontInstance {},
	Touch: class extends self.IInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	SandTopTexture2: class extends self.ITiledBackgroundInstance {},
	_3DObject2: class extends self.IWorldInstance {},
	_3DObject: class extends self.IWorldInstance {},
	_3DObject3: class extends self.IWorldInstance {},
	Audio: class extends self.IInstance {},
	_3DObject4: class extends self.IWorldInstance {},
	_3DObject5: class extends self.IWorldInstance {},
	GamePlayer: class extends self.IWorldInstance {},
	GameScoreFont: class extends self.ISpriteFontInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	gameplayers: class extends self.ISpriteFontInstance {},
	Soundsprite: class extends self.ISpriteInstance {},
	restartbtn: class extends self.ISpriteInstance {},
	Sprite2sp: class extends self.ISpriteInstance {},
	PlayerColliderBot1: class extends self.ISpriteInstance {},
	BotPlayer1: class extends self.IWorldInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Counter: class extends self.ISpriteInstance {},
	Blood: class extends self.ISpriteInstance {},
	Bloodmodel: class extends self.I3DShapeInstance {},
	PlayerModel2: class extends self.I3DShapeInstance {},
	_3DShape: class extends self.I3DShapeInstance {},
	Playerarrow: class extends self.I3DShapeInstance {},
	arrow: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	gameroundfont: class extends self.ISpriteFontInstance {},
	light: class extends self.ISpriteInstance {},
	gameover: class extends self.ISpriteInstance {},
	RESTART: class extends self.ISpriteInstance {},
	MENU: class extends self.ISpriteInstance {},
	gameoverscore: class extends self.ISpriteFontInstance {},
	ValerypopoffJS: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Roundcompleted: class extends self.ISpriteInstance {},
	Roundcompleted2: class extends self.ISpriteInstance {},
	Winscore: class extends self.ISpriteFontInstance {},
	MENU2: class extends self.ISpriteInstance {},
	botshadow1: class extends self.ISpriteInstance {},
	PlayerColliderBot2: class extends self.ISpriteInstance {},
	BotPlayer2: class extends self.IWorldInstance {},
	botshadow2: class extends self.ISpriteInstance {},
	PlayerColliderBot3: class extends self.ISpriteInstance {},
	BotPlayer3: class extends self.IWorldInstance {},
	botshadow3: class extends self.ISpriteInstance {},
	PlayerColliderBot4: class extends self.ISpriteInstance {},
	BotPlayer4: class extends self.IWorldInstance {},
	botshadow4: class extends self.ISpriteInstance {},
	PlayerColliderBot5: class extends self.ISpriteInstance {},
	BotPlayer5: class extends self.IWorldInstance {},
	botshadow5: class extends self.ISpriteInstance {},
	PlayerColliderBot6: class extends self.ISpriteInstance {},
	BotPlayer6: class extends self.IWorldInstance {},
	botshadow6: class extends self.ISpriteInstance {},
	PlayerColliderBot7: class extends self.ISpriteInstance {},
	BotPlayer7: class extends self.IWorldInstance {},
	botshadow7: class extends self.ISpriteInstance {},
	PlayerColliderBot8: class extends self.ISpriteInstance {},
	BotPlayer8: class extends self.IWorldInstance {},
	botshadow8: class extends self.ISpriteInstance {},
	PlayerColliderBot9: class extends self.ISpriteInstance {},
	BotPlayer9: class extends self.IWorldInstance {},
	botshadow9: class extends self.ISpriteInstance {},
	Bot1arrow: class extends self.I3DShapeInstance {},
	botnumber1: class extends self.ISpriteInstance {},
	botnumber2: class extends self.ISpriteInstance {},
	Bot1arrow2: class extends self.I3DShapeInstance {},
	botnumber3: class extends self.ISpriteInstance {},
	Bot1arrow3: class extends self.I3DShapeInstance {},
	botnumber4: class extends self.ISpriteInstance {},
	Bot1arrow4: class extends self.I3DShapeInstance {},
	botnumber5: class extends self.ISpriteInstance {},
	Bot1arrow5: class extends self.I3DShapeInstance {},
	botnumber6: class extends self.ISpriteInstance {},
	Bot1arrow6: class extends self.I3DShapeInstance {},
	botnumber7: class extends self.ISpriteInstance {},
	Bot1arrow7: class extends self.I3DShapeInstance {},
	botnumber8: class extends self.ISpriteInstance {},
	Bot1arrow8: class extends self.I3DShapeInstance {},
	botnumber9: class extends self.ISpriteInstance {},
	Bot1arrow9: class extends self.I3DShapeInstance {},
	enemyshadow: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Youwin: class extends self.ISpriteInstance {},
	ScoreDisplay: class extends self.ITextInstance {},
	Multiplayer: class extends self.IInstance {},
	PlayerCollider2: class extends self.ISpriteInstance {},
	LogText: class extends self.ITextInstance {},
	LogMessages: class extends self.IArrayInstance {},
	NetStats: class extends self.ITextInstance {},
	tracker: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	GamePlayer2: class extends self.IWorldInstance {},
	PlayerShadow2: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Timer: class extends self.ISpriteFontInstance {},
	p1: class extends self.ISpriteInstance {},
	p2: class extends self.ISpriteInstance {},
	p3: class extends self.ISpriteInstance {},
	p4: class extends self.ISpriteInstance {}
}