const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Rotate,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.Text,
		C3.Plugins.Particles,
		C3.Behaviors.Pin,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.TiledBg.Acts.SetAngle,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.ToggleBoolInstanceVar,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetFlipped,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Text.Acts.AddInstanceVar,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.TiledBg.Cnds.CompareOpacity,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.SetSilent
	];
};
self.C3_JsPropNameTable = [
	{TiledBackground: 0},
	{Asset: 0},
	{Asset2: 0},
	{Asset3: 0},
	{Asset4: 0},
	{Asset5: 0},
	{Asset6: 0},
	{Asset7: 0},
	{Asset8: 0},
	{Asset9: 0},
	{Asset10: 0},
	{Asset11: 0},
	{Asset12: 0},
	{Asset13: 0},
	{Asset14: 0},
	{Tween: 0},
	{TiledBackground2: 0},
	{Left: 0},
	{Ready: 0},
	{character: 0},
	{Asset15: 0},
	{Asset16: 0},
	{Rotate: 0},
	{Asset17: 0},
	{Asset18: 0},
	{Touch: 0},
	{Audio: 0},
	{LocalStorage: 0},
	{pos: 0},
	{Sprite: 0},
	{score: 0},
	{speed: 0},
	{Text: 0},
	{Asset19: 0},
	{Particles: 0},
	{TiledBackground3: 0},
	{Asset20: 0},
	{TiledBackground4: 0},
	{Asset21: 0},
	{Asset22: 0},
	{Asset23: 0},
	{Asset24: 0},
	{Asset25: 0},
	{Asset26: 0},
	{Pin: 0},
	{Text2: 0},
	{Text3: 0},
	{TFamily: 0},
	{BEST: 0},
	{LastScore: 0},
	{Timer: 0},
	{Form: 0},
	{Mute: 0}
];

self.InstanceType = {
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Asset: class extends self.ISpriteInstance {},
	Asset2: class extends self.ISpriteInstance {},
	Asset3: class extends self.ISpriteInstance {},
	Asset4: class extends self.ISpriteInstance {},
	Asset5: class extends self.ISpriteInstance {},
	Asset6: class extends self.ISpriteInstance {},
	Asset7: class extends self.ISpriteInstance {},
	Asset8: class extends self.ISpriteInstance {},
	Asset9: class extends self.ISpriteInstance {},
	Asset10: class extends self.ISpriteInstance {},
	Asset11: class extends self.ISpriteInstance {},
	Asset12: class extends self.ISpriteInstance {},
	Asset13: class extends self.ISpriteInstance {},
	Asset14: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	character: class extends self.ISpriteInstance {},
	Asset15: class extends self.ISpriteInstance {},
	Asset16: class extends self.ISpriteInstance {},
	Asset17: class extends self.ISpriteInstance {},
	Asset18: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Asset19: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	Asset20: class extends self.ISpriteInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	Asset21: class extends self.ISpriteInstance {},
	Asset22: class extends self.ISpriteInstance {},
	Asset23: class extends self.ISpriteInstance {},
	Asset24: class extends self.ISpriteInstance {},
	Asset25: class extends self.ISpriteInstance {},
	Asset26: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	TFamily: class extends self.ISpriteInstance {}
}