var CANVAS_WIDTH = 1280;
var CANVAS_HEIGHT = 768;

var EDGEBOARD_X = 90;
var EDGEBOARD_Y = 105;

var FPS = 30;
var FPS_TIME      = 1000/FPS;
var DISABLE_SOUND_MOBILE = false;

var PRIMARY_FONT = "arialbold";

var STATE_LOADING = 0;
var STATE_MENU    = 1;
var STATE_HELP    = 1;
var STATE_GAME    = 3;

var ON_MOUSE_DOWN  = 0;
var ON_MOUSE_UP    = 1;
var ON_MOUSE_OVER  = 2;
var ON_MOUSE_OUT   = 3;
var ON_DRAG_START  = 4;
var ON_DRAG_END    = 5;
var ON_CONTROLLER_END    = 8;
var ON_CONTROLLER_REMOVE = 9;
var ON_CONTROLLER_ROLL = 10;

var PLAYER_IDLE = 0;
var PLAYER_AIM = 1;
var PLAYER_RECHARGE = 2;
var PLAYER_SHOOT = 3;

var SKEET_AWAY = 0;
var SKEET_LINEAR = 1;
var SKEET_PARABOLIC = 2;

var SKEET_GONE = 0;
var SKEET_DESTROYED = 1;

var MAX_NUM_AMMO = 2;

var SHOT_SINGLE = 0;
var SHOT_DOUBLE = 1;

var STANDARD_SPEED_FACTOR;

var MOBILE_SPEED_FACTOR; //GREATER NUMBERS IS SLOWER
var TRAJECTOR_RANGE_X = 100;
var TRAJECTOR_RANGE_Y = 50;

var SCOPE_ACCELERATION;
var SCOPE_FRICTION;
var MAX_SCOPE_SPEED;

var MAX_POINTS_EARN;

var ENABLE_FULLSCREEN;
var ENABLE_CHECK_ORIENTATION;
var AD_SHOW_COUNTER;
var SOUNDTRACK_VOLUME_IN_GAME = 1;