const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Button,
		C3.Plugins.Text,
		C3.Plugins.TextBox,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.EightDir,
		C3.Plugins.Arr,
		C3.Behaviors.Bullet,
		C3.Plugins.TiledBg,
		C3.Plugins.Multiplayer,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.Particles,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.Arr.Acts.Pop,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Text.Acts.AppendText,
		C3.Plugins.Arr.Exps.CurValue,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Multiplayer.Acts.AddClientInputValue,
		C3.Plugins.Multiplayer.Acts.SyncObject,
		C3.Plugins.Multiplayer.Acts.SyncObjectInstanceVar,
		C3.Plugins.Multiplayer.Acts.SyncObject2,
		C3.Plugins.Multiplayer.Acts.SignallingConnect,
		C3.Plugins.Multiplayer.Cnds.OnSignallingConnected,
		C3.Plugins.Multiplayer.Acts.SignallingLogin,
		C3.Plugins.Multiplayer.Cnds.OnSignallingLoggedIn,
		C3.Plugins.Multiplayer.Exps.MyAlias,
		C3.Plugins.Multiplayer.Exps.MyID,
		C3.Plugins.Multiplayer.Acts.SignallingAutoJoinRoom,
		C3.Plugins.Multiplayer.Cnds.OnSignallingJoinedRoom,
		C3.Plugins.Multiplayer.Cnds.IsHost,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Multiplayer.Acts.AssociateObjectWithPeer,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Multiplayer.Cnds.OnSignallingDisconnected,
		C3.Plugins.Multiplayer.Cnds.OnSignallingError,
		C3.Plugins.Multiplayer.Exps.ErrorMessage,
		C3.Plugins.Multiplayer.Cnds.OnSignallingLeftRoom,
		C3.Plugins.Multiplayer.Cnds.OnSignallingKicked,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Multiplayer.Exps.StatInboundCount,
		C3.Plugins.Multiplayer.Exps.StatInboundBandwidth,
		C3.Plugins.Multiplayer.Exps.StatOutboundCount,
		C3.Plugins.Multiplayer.Exps.StatOutboundBandwidth,
		C3.Plugins.Multiplayer.Exps.PeerLatency,
		C3.Plugins.Multiplayer.Exps.HostID,
		C3.Plugins.Multiplayer.Exps.PeerPDV,
		C3.Plugins.Multiplayer.Cnds.OnPeerConnected,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Multiplayer.Exps.PeerID,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Multiplayer.Acts.HostBroadcastMessage,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Bullet.Cnds.CompareSpeed,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Exps.Speed,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Multiplayer.Exps.PeerState,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.getbit,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Multiplayer.Acts.InputPredictObject,
		C3.Plugins.Multiplayer.Cnds.OnPeerMessage,
		C3.Plugins.Multiplayer.Exps.Message,
		C3.Plugins.Multiplayer.Cnds.OnClientUpdate,
		C3.Plugins.System.Exps.setbit,
		C3.Plugins.Multiplayer.Acts.SetClientState,
		C3.Plugins.Multiplayer.Exps.PeerAlias,
		C3.Plugins.Multiplayer.Cnds.OnPeerDisconnected,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Multiplayer.Exps.HostAlias,
		C3.Plugins.Multiplayer.Exps.PeerAliasFromID,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Multiplayer.Acts.DisconnectRoom,
		C3.Plugins.Multiplayer.Acts.SignallingDisconnect,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Text.Acts.SetVisible,
		C3.JavaScriptInEvents.GameEvents_Event69_Act2,
		C3.JavaScriptInEvents.GameEvents_Event69_Act5,
		C3.Plugins.TextBox.Acts.SetFocus,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.Button.Acts.SetCSSStyle,
		C3.Plugins.Multiplayer.Cnds.IsSupported,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.TextBox.Cnds.OnTextChanged,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Plugins.Button.Acts.SetEnabled,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Audio.Acts.StopAll
	];
};
self.C3_JsPropNameTable = [
	{JoinButton: 0},
	{Title: 0},
	{NameTextBox: 0},
	{FormLabel: 0},
	{NetStats: 0},
	{peerid: 0},
	{points: 0},
	{inputs: 0},
	{Solid: 0},
	{"8Direction": 0},
	{Paddle: 0},
	{LogText: 0},
	{LogMessages: 0},
	{Bullet: 0},
	{Ball: 0},
	{Barrier: 0},
	{ScoreDisplay: 0},
	{Particles_on_collision: 0},
	{Username_peer: 0},
	{Username_host: 0},
	{Multiplayer: 0},
	{Mouse: 0},
	{Keyboard: 0},
	{court_: 0},
	{goal_posts_left: 0},
	{Host_Goals_Counter: 0},
	{Peer_Goals_Counter: 0},
	{Particles: 0},
	{Audio: 0},
	{btn_close: 0},
	{Touch: 0},
	{Left_touch: 0},
	{Right_touch: 0},
	{arrowLeft: 0},
	{arrowRight: 0},
	{musicOn: 0},
	{text_goal: 0},
	{text_win_host: 0},
	{text_win_peer: 0},
	{GAME_NAME: 0},
	{INSTANCE_NAME: 0},
	{ROOM_NAME: 0},
	{BallSpeed: 0},
	{Score_to_Win: 0},
	{GameState: 0},
	{message: 0},
	{state: 0},
	{MyUsername: 0}
];

self.InstanceType = {
	JoinButton: class extends self.IButtonInstance {},
	Title: class extends self.ITextInstance {},
	NameTextBox: class extends self.ITextInputInstance {},
	FormLabel: class extends self.ITextInstance {},
	NetStats: class extends self.ITextInstance {},
	Paddle: class extends self.ISpriteInstance {},
	LogText: class extends self.ITextInstance {},
	LogMessages: class extends self.IArrayInstance {},
	Ball: class extends self.ISpriteInstance {},
	Barrier: class extends self.ITiledBackgroundInstance {},
	ScoreDisplay: class extends self.ITextInstance {},
	Particles_on_collision: class extends self.ISpriteInstance {},
	Username_peer: class extends self.ITextInstance {},
	Username_host: class extends self.ITextInstance {},
	Multiplayer: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	court_: class extends self.ISpriteInstance {},
	goal_posts_left: class extends self.ISpriteInstance {},
	Host_Goals_Counter: class extends self.ITextInstance {},
	Peer_Goals_Counter: class extends self.ITextInstance {},
	Particles: class extends self.IParticlesInstance {},
	Audio: class extends self.IInstance {},
	btn_close: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Left_touch: class extends self.ISpriteInstance {},
	Right_touch: class extends self.ISpriteInstance {},
	arrowLeft: class extends self.ISpriteInstance {},
	arrowRight: class extends self.ISpriteInstance {},
	musicOn: class extends self.ISpriteInstance {},
	text_goal: class extends self.ISpriteInstance {},
	text_win_host: class extends self.ISpriteInstance {},
	text_win_peer: class extends self.ISpriteInstance {}
}