const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.Browser,
		C3.Plugins.Text,
		C3.Behaviors.lunarray_LiteTween,
		C3.Behaviors.Pin,
		C3.Behaviors.Fade,
		C3.Plugins.TiledBg,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Persist,
		C3.Plugins.video,
		C3.Behaviors.Rotate,
		C3.Plugins.Particles,
		C3.Plugins.Timeline,
		C3.Plugins.Spritefont2,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.lunarray_LiteTween.Acts.Start,
		C3.Behaviors.lunarray_LiteTween.Cnds.IsActive,
		C3.Behaviors.lunarray_LiteTween.Cnds.IsReversing,
		C3.Behaviors.lunarray_LiteTween.Acts.Reverse,
		C3.Plugins.Sprite.Acts.ToggleBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.lunarray_LiteTween.Cnds.OnReverseEnd,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.SetEffect,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Sin.Acts.SetPhase,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Exps.IID,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Cnds.PickOverlappingPoint,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Cnds.PickNth,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Exps.Width,
		C3.JavaScriptInEvents.Game_Event263_Act4,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.TiledBg.Cnds.CompareY,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.video.Cnds.HasEnded,
		C3.Plugins.Browser.Cnds.IsOnline
	];
};
self.C3_JsPropNameTable = [
	{AJAX: 0},
	{JSON: 0},
	{Sine: 0},
	{Title: 0},
	{Play_Button: 0},
	{Menu_Background: 0},
	{Touch: 0},
	{Audio: 0},
	{LocalStorage: 0},
	{Browser: 0},
	{Menu_Button_Map: 0},
	{Level: 0},
	{Levels_Buttons: 0},
	{Levels_Numbers: 0},
	{Pause: 0},
	{Game_Background: 0},
	{level: 0},
	{Level_Text: 0},
	{Timer: 0},
	{Mission_1_Text: 0},
	{Mission_3_Text: 0},
	{Mission_2_Text: 0},
	{ID: 0},
	{Total_Destroyed: 0},
	{Mission_Candies: 0},
	{occupy: 0},
	{back_plate: 0},
	{h_span: 0},
	{v_span: 0},
	{h_test: 0},
	{v_test: 0},
	{put_h: 0},
	{put_v: 0},
	{trap_on: 0},
	{Arrows: 0},
	{Spaces: 0},
	{done: 0},
	{disappear: 0},
	{move: 0},
	{pop: 0},
	{matchX: 0},
	{matchY: 0},
	{locked: 0},
	{x_combo: 0},
	{y_combo: 0},
	{matched: 0},
	{settled: 0},
	{velocity: 0},
	{stop_pos: 0},
	{color: 0},
	{order: 0},
	{combo_matcher: 0},
	{x_counter: 0},
	{y_counter: 0},
	{moveto: 0},
	{candy: 0},
	{score: 0},
	{target: 0},
	{Marker: 0},
	{Sensor: 0},
	{column: 0},
	{open: 0},
	{portal: 0},
	{col_size: 0},
	{full: 0},
	{max_stack: 0},
	{trap_on_line: 0},
	{top_trap: 0},
	{lets_count: 0},
	{Scanner: 0},
	{Y_Matcher: 0},
	{X_Matcher: 0},
	{horizontal: 0},
	{strip: 0},
	{vertical: 0},
	{free: 0},
	{tagged: 0},
	{pick_candy: 0},
	{cycle: 0},
	{trap_slide: 0},
	{downline: 0},
	{counted: 0},
	{Dot: 0},
	{Mission_Start_Level: 0},
	{Lose_Retry: 0},
	{LiteTween: 0},
	{Lose_Panel: 0},
	{Mission_Panel: 0},
	{Lose_Home: 0},
	{Score: 0},
	{Pause_Exit: 0},
	{Pause_Restart: 0},
	{Pause_Menu: 0},
	{Pause_Resume: 0},
	{Pause_Box: 0},
	{Grey: 0},
	{Mission_Exit: 0},
	{Pin: 0},
	{Mission_Items_Count: 0},
	{Mission_Items_Icons: 0},
	{Settings: 0},
	{Settings_Panel: 0},
	{Settings_Exit: 0},
	{Fade: 0},
	{Match_Effect: 0},
	{Win_BestScore: 0},
	{Win_Panel: 0},
	{Win_Exit: 0},
	{Win_Score: 0},
	{Win_Restart: 0},
	{Win_Next: 0},
	{Level_Stars: 0},
	{Stars: 0},
	{DragDrop: 0},
	{Map2: 0},
	{paperForTarget: 0},
	{x: 0},
	{Win_Menu: 0},
	{Win_Results_Stars: 0},
	{On: 0},
	{Persist: 0},
	{Music_Button: 0},
	{Sound_Button: 0},
	{Available: 0},
	{Powerup_Bomb: 0},
	{Powerups_Buttons: 0},
	{Powerup_Arrows: 0},
	{Powerup_Hammer: 0},
	{Mission_Icon: 0},
	{Mission_Small_Box: 0},
	{Video: 0},
	{Sprite: 0},
	{adl_update_available: 0},
	{v: 0},
	{adl_version_shower: 0},
	{adl_Text2: 0},
	{adl_loading_Text: 0},
	{adl_loadingadtext: 0},
	{adl_white_back: 0},
	{adl_update_button: 0},
	{adl_installgamebutton: 0},
	{adl_blocker: 0},
	{Rotate: 0},
	{adl_loading_logo_rotate: 0},
	{adl_separater: 0},
	{adl_back: 0},
	{Sprite2: 0},
	{Sprite4: 0},
	{Sprite3: 0},
	{Sprite7: 0},
	{LevelParticles: 0},
	{Sprite8: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{sb: 0},
	{story_text: 0},
	{Sprite12: 0},
	{skip_text: 0},
	{skip_button: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{TimelineController: 0},
	{loader_bg: 0},
	{loadingbar_back: 0},
	{loadingbar_progress: 0},
	{GAMELAUNCHER: 0},
	{loading_text: 0},
	{loading_text_percent: 0},
	{Sprite16: 0},
	{Pins: 0},
	{Mission_Items: 0},
	{Lose_Items: 0},
	{Pause_Items: 0},
	{Buttons: 0},
	{Settings_Items: 0},
	{Win_Items: 0},
	{Power_Used: 0},
	{Phase: 0},
	{Points: 0},
	{Mission_Points: 0},
	{Mission_1: 0},
	{Mission_2: 0},
	{Mission_3: 0},
	{Mission_1_Progress: 0},
	{Mission_2_Progress: 0},
	{Mission_3_Progress: 0},
	{Pts_Multiplier: 0},
	{Seconds: 0},
	{Minutes: 0},
	{Candies: 0},
	{Stack_Checker: 0},
	{horizontal_color: 0},
	{vertical_color: 0},
	{Scanner_Checker: 0},
	{Exploded_Color: 0},
	{Destroyed_Amount: 0},
	{X: 0},
	{Xa: 0},
	{Xb: 0},
	{Y: 0},
	{Ya: 0},
	{Yb: 0},
	{n: 0},
	{Frame: 0},
	{dx: 0},
	{dy: 0},
	{check_color: 0},
	{Frame_Destroy: 0},
	{Star_1: 0},
	{Star_2: 0},
	{Star_3: 0},
	{Level_Reached: 0},
	{Sounds_Volume: 0},
	{Sounds: 0},
	{Music_Volume: 0},
	{Score_Level_1: 0},
	{Score_Level_2: 0},
	{Score_Level_3: 0},
	{Score_Level_4: 0},
	{Score_Level_5: 0},
	{Score_Level_6: 0},
	{Score_Level_7: 0},
	{Score_Level_8: 0},
	{Score_Level_9: 0},
	{Score_Level_10: 0},
	{Score_Level_11: 0},
	{Score_Level_12: 0},
	{Score_Level_13: 0},
	{Score_Level_14: 0},
	{Score_Level_15: 0},
	{Score_Level_16: 0},
	{Score_Level_17: 0},
	{Score_Level_18: 0},
	{Score_Level_19: 0},
	{Score_Level_20: 0},
	{Score_Level_21: 0},
	{Score_Level_22: 0},
	{Score_Level_23: 0},
	{Score_Level_24: 0},
	{Score_Level_25: 0}
];

self.InstanceType = {
	AJAX: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	Title: class extends self.ISpriteInstance {},
	Play_Button: class extends self.ISpriteInstance {},
	Menu_Background: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Menu_Button_Map: class extends self.ISpriteInstance {},
	Levels_Buttons: class extends self.ISpriteInstance {},
	Levels_Numbers: class extends self.ISpriteInstance {},
	Pause: class extends self.ISpriteInstance {},
	Game_Background: class extends self.ISpriteInstance {},
	level: class extends self.ISpriteInstance {},
	Level_Text: class extends self.ITextInstance {},
	Timer: class extends self.ITextInstance {},
	Mission_1_Text: class extends self.ITextInstance {},
	Mission_3_Text: class extends self.ITextInstance {},
	Mission_2_Text: class extends self.ITextInstance {},
	Mission_Candies: class extends self.ISpriteInstance {},
	Spaces: class extends self.ISpriteInstance {},
	candy: class extends self.ISpriteInstance {},
	Marker: class extends self.ISpriteInstance {},
	Sensor: class extends self.ISpriteInstance {},
	portal: class extends self.ISpriteInstance {},
	Scanner: class extends self.ISpriteInstance {},
	Y_Matcher: class extends self.ISpriteInstance {},
	X_Matcher: class extends self.ISpriteInstance {},
	horizontal: class extends self.ISpriteInstance {},
	strip: class extends self.ISpriteInstance {},
	vertical: class extends self.ISpriteInstance {},
	Dot: class extends self.ISpriteInstance {},
	Mission_Start_Level: class extends self.ISpriteInstance {},
	Lose_Retry: class extends self.ISpriteInstance {},
	Lose_Panel: class extends self.ISpriteInstance {},
	Mission_Panel: class extends self.ISpriteInstance {},
	Lose_Home: class extends self.ISpriteInstance {},
	Score: class extends self.ITextInstance {},
	Pause_Exit: class extends self.ISpriteInstance {},
	Pause_Restart: class extends self.ISpriteInstance {},
	Pause_Menu: class extends self.ISpriteInstance {},
	Pause_Resume: class extends self.ISpriteInstance {},
	Pause_Box: class extends self.ISpriteInstance {},
	Grey: class extends self.ISpriteInstance {},
	Mission_Exit: class extends self.ISpriteInstance {},
	Mission_Items_Count: class extends self.ITextInstance {},
	Mission_Items_Icons: class extends self.ISpriteInstance {},
	Settings: class extends self.ISpriteInstance {},
	Settings_Panel: class extends self.ISpriteInstance {},
	Settings_Exit: class extends self.ISpriteInstance {},
	Match_Effect: class extends self.ISpriteInstance {},
	Win_BestScore: class extends self.ITextInstance {},
	Win_Panel: class extends self.ISpriteInstance {},
	Win_Exit: class extends self.ISpriteInstance {},
	Win_Score: class extends self.ITextInstance {},
	Win_Restart: class extends self.ISpriteInstance {},
	Win_Next: class extends self.ISpriteInstance {},
	Stars: class extends self.ISpriteInstance {},
	Map2: class extends self.ITiledBackgroundInstance {},
	paperForTarget: class extends self.ISpriteInstance {},
	x: class extends self.ISpriteInstance {},
	Win_Menu: class extends self.ISpriteInstance {},
	Win_Results_Stars: class extends self.ISpriteInstance {},
	Music_Button: class extends self.ISpriteInstance {},
	Sound_Button: class extends self.ISpriteInstance {},
	Powerup_Bomb: class extends self.ISpriteInstance {},
	Powerups_Buttons: class extends self.ISpriteInstance {},
	Powerup_Arrows: class extends self.ISpriteInstance {},
	Powerup_Hammer: class extends self.ISpriteInstance {},
	Mission_Icon: class extends self.ISpriteInstance {},
	Mission_Small_Box: class extends self.ISpriteInstance {},
	Video: class extends self.IWorldInstance {},
	Sprite: class extends self.ISpriteInstance {},
	adl_update_available: class extends self.ITextInstance {},
	adl_version_shower: class extends self.ITextInstance {},
	adl_Text2: class extends self.ITextInstance {},
	adl_loading_Text: class extends self.ITextInstance {},
	adl_loadingadtext: class extends self.ITextInstance {},
	adl_white_back: class extends self.ISpriteInstance {},
	adl_update_button: class extends self.ISpriteInstance {},
	adl_installgamebutton: class extends self.ISpriteInstance {},
	adl_blocker: class extends self.ISpriteInstance {},
	adl_loading_logo_rotate: class extends self.ISpriteInstance {},
	adl_separater: class extends self.ISpriteInstance {},
	adl_back: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	LevelParticles: class extends self.IParticlesInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	sb: class extends self.ISpriteInstance {},
	story_text: class extends self.ITextInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	skip_text: class extends self.ISpriteInstance {},
	skip_button: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	TimelineController: class extends self.IInstance {},
	loader_bg: class extends self.ISpriteInstance {},
	loadingbar_back: class extends self.ITiledBackgroundInstance {},
	loadingbar_progress: class extends self.ITiledBackgroundInstance {},
	GAMELAUNCHER: class extends self.ISpriteInstance {},
	loading_text: class extends self.ISpriteFontInstance {},
	loading_text_percent: class extends self.ISpriteFontInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Pins: class extends self.ISpriteInstance {},
	Mission_Items: class extends self.ISpriteInstance {},
	Lose_Items: class extends self.ISpriteInstance {},
	Pause_Items: class extends self.ISpriteInstance {},
	Buttons: class extends self.ISpriteInstance {},
	Settings_Items: class extends self.ISpriteInstance {},
	Win_Items: class extends self.ISpriteInstance {}
}