var CANVAS_WIDTH = 968;
var CANVAS_HEIGHT = 1224;

var EDGEBOARD_X = 100;
var EDGEBOARD_Y = 50;

var FONT_GAME = "arialbold";

var DISABLE_SOUND_MOBILE = false;

var FPS_TIME      = 1000/24;

var STATE_LOADING = 0;
var STATE_MENU    = 1;
var STATE_HELP    = 1;
var STATE_GAME    = 3;

var ON_MOUSE_DOWN = 0;
var ON_MOUSE_UP   = 1;
var ON_MOUSE_OVER = 2;
var ON_MOUSE_OUT  = 3;
var ON_DRAG_START = 4;
var ON_DRAG_END   = 5;

var NUM_LINES = 2;
var MAX_STARTING_SPEED;
var INCREASE_SPEED_UP_INTERVAL;
var INCREASE_SPEED;
var DISTANCE_AMONG_OBSTACLES;
var ACCELLERATION;
var SCORE_INCREASE;
var MALUS_SCORE;
var NUM_LIVES;

var ENABLE_FULLSCREEN;
var ENABLE_CHECK_ORIENTATION;