const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Sprite,
		C3.Behaviors.lunarray_LiteTween,
		C3.Behaviors.Rotate,
		C3.Plugins.Spritefont2,
		C3.Behaviors.bound,
		C3.Behaviors.EightDir,
		C3.Behaviors.solid,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.scrollto,
		C3.Behaviors.Sin,
		C3.Behaviors.Fade,
		C3.Plugins.Function,
		C3.Plugins.TiledBg,
		C3.Plugins.LocalStorage,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.TiledBg.Acts.SetHeight,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Exps.viewportright,
		C3.Behaviors.lunarray_LiteTween.Acts.Start,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.Function.Acts.SetReturnValue,
		C3.Plugins.System.Exps.canvastolayerx,
		C3.Plugins.Touch.Exps.AbsoluteXForID,
		C3.Plugins.Function.Exps.Param,
		C3.Plugins.Touch.Exps.AbsoluteYForID,
		C3.Plugins.System.Exps.canvastolayery,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Touch.Exps.TouchID,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Function.Exps.Call,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Behaviors.lunarray_LiteTween.Acts.SetTarget,
		C3.Behaviors.lunarray_LiteTween.Acts.SetDuration,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.SetY,
		C3.ScriptsInEvents.Gamesettings_Event133_Act2,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Audio.Acts.Preload,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{Audio: 0},
	{Browser: 0},
	{LiteTween: 0},
	{BtnMoreGames: 0},
	{BtnMusic: 0},
	{BtnSound: 0},
	{Background1: 0},
	{BtnPlay: 0},
	{BtnInfo: 0},
	{Rotate: 0},
	{SunLight: 0},
	{LoadingFont: 0},
	{BtnRestart: 0},
	{BtnPause: 0},
	{Cursor: 0},
	{CursorHover: 0},
	{ScoreFont1: 0},
	{HighScoreFont: 0},
	{LastScoreFont: 0},
	{TimeFont1: 0},
	{BoundToLayout: 0},
	{"8Direction": 0},
	{Solid: 0},
	{DragDrop: 0},
	{ScrollTo: 0},
	{Player: 0},
	{Sine: 0},
	{Enemy3: 0},
	{Enemy2: 0},
	{Enemy1: 0},
	{Rocket: 0},
	{Explosion1: 0},
	{Cloud1: 0},
	{Cloud3: 0},
	{Cloud2: 0},
	{Collision: 0},
	{Star: 0},
	{Fade: 0},
	{Score500: 0},
	{Score250: 0},
	{Score100: 0},
	{Score125: 0},
	{XP: 0},
	{YP: 0},
	{ConAngle: 0},
	{Joystick: 0},
	{JoystickArea: 0},
	{Function: 0},
	{PlayerCollision: 0},
	{Cloud4: 0},
	{Background2: 0},
	{BackgroundsBack: 0},
	{Frame: 0},
	{AddAmmo: 0},
	{AddFuel: 0},
	{AddLife: 0},
	{AmmoBar: 0},
	{FuelBar: 0},
	{LifeBar: 0},
	{BarBackground: 0},
	{LifeBarLine: 0},
	{AmmoBarLine: 0},
	{FuelBarLIne: 0},
	{RocketBar: 0},
	{RocketBarLine: 0},
	{AddRocket: 0},
	{Bullet: 0},
	{Enemy4: 0},
	{Enemy5: 0},
	{Enemy2Menu: 0},
	{Enemy3Menu: 0},
	{Enemy1Menu: 0},
	{GameLogo: 0},
	{Enemy6: 0},
	{FrameTime: 0},
	{TimeFont: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{ScoreFont: 0},
	{Sprite3: 0},
	{FrameTimeArrow: 0},
	{Explosion: 0},
	{ExitApp: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{effect_level: 0},
	{effectleft: 0},
	{effectright: 0},
	{Effectgameover: 0},
	{ArmazenamentoLocal: 0},
	{MouseOver: 0},
	{ButtonsSound: 0},
	{Pause: 0},
	{Score: 0},
	{Life: 0},
	{Fuel: 0},
	{Seconds: 0},
	{Minutes: 0},
	{LastScore: 0},
	{HighScore: 0},
	{Background: 0},
	{RocketAmmo: 0},
	{BulletAmmo: 0},
	{TouchID: 0},
	{Dist: 0},
	{Cangle: 0},
	{Radius: 0},
	{DeadZone: 0},
	{Sound: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	BtnMoreGames: class extends self.ISpriteInstance {},
	BtnMusic: class extends self.ISpriteInstance {},
	BtnSound: class extends self.ISpriteInstance {},
	Background1: class extends self.ISpriteInstance {},
	BtnPlay: class extends self.ISpriteInstance {},
	BtnInfo: class extends self.ISpriteInstance {},
	SunLight: class extends self.ISpriteInstance {},
	LoadingFont: class extends self.ISpriteFontInstance {},
	BtnRestart: class extends self.ISpriteInstance {},
	BtnPause: class extends self.ISpriteInstance {},
	Cursor: class extends self.ISpriteInstance {},
	CursorHover: class extends self.ISpriteInstance {},
	ScoreFont1: class extends self.ISpriteFontInstance {},
	HighScoreFont: class extends self.ISpriteFontInstance {},
	LastScoreFont: class extends self.ISpriteFontInstance {},
	TimeFont1: class extends self.ISpriteFontInstance {},
	Player: class extends self.ISpriteInstance {},
	Enemy3: class extends self.ISpriteInstance {},
	Enemy2: class extends self.ISpriteInstance {},
	Enemy1: class extends self.ISpriteInstance {},
	Rocket: class extends self.ISpriteInstance {},
	Explosion1: class extends self.ISpriteInstance {},
	Cloud1: class extends self.ISpriteInstance {},
	Cloud3: class extends self.ISpriteInstance {},
	Cloud2: class extends self.ISpriteInstance {},
	Collision: class extends self.ISpriteInstance {},
	Star: class extends self.ISpriteInstance {},
	Score500: class extends self.ISpriteInstance {},
	Score250: class extends self.ISpriteInstance {},
	Score100: class extends self.ISpriteInstance {},
	Score125: class extends self.ISpriteInstance {},
	Joystick: class extends self.ISpriteInstance {},
	JoystickArea: class extends self.ISpriteInstance {},
	Function: class extends self.IInstance {},
	PlayerCollision: class extends self.ISpriteInstance {},
	Cloud4: class extends self.ISpriteInstance {},
	Background2: class extends self.ISpriteInstance {},
	BackgroundsBack: class extends self.ITiledBackgroundInstance {},
	Frame: class extends self.ISpriteInstance {},
	AddAmmo: class extends self.ISpriteInstance {},
	AddFuel: class extends self.ISpriteInstance {},
	AddLife: class extends self.ISpriteInstance {},
	AmmoBar: class extends self.ISpriteInstance {},
	FuelBar: class extends self.ISpriteInstance {},
	LifeBar: class extends self.ISpriteInstance {},
	BarBackground: class extends self.ISpriteInstance {},
	LifeBarLine: class extends self.ISpriteInstance {},
	AmmoBarLine: class extends self.ISpriteInstance {},
	FuelBarLIne: class extends self.ISpriteInstance {},
	RocketBar: class extends self.ISpriteInstance {},
	RocketBarLine: class extends self.ISpriteInstance {},
	AddRocket: class extends self.ISpriteInstance {},
	Bullet: class extends self.ISpriteInstance {},
	Enemy4: class extends self.ISpriteInstance {},
	Enemy5: class extends self.ISpriteInstance {},
	Enemy2Menu: class extends self.ISpriteInstance {},
	Enemy3Menu: class extends self.ISpriteInstance {},
	Enemy1Menu: class extends self.ISpriteInstance {},
	GameLogo: class extends self.ISpriteInstance {},
	Enemy6: class extends self.ISpriteInstance {},
	FrameTime: class extends self.ISpriteInstance {},
	TimeFont: class extends self.ISpriteFontInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	ScoreFont: class extends self.ISpriteFontInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	FrameTimeArrow: class extends self.ISpriteInstance {},
	Explosion: class extends self.ISpriteInstance {},
	ExitApp: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	effect_level: class extends self.ISpriteInstance {},
	effectleft: class extends self.ISpriteInstance {},
	effectright: class extends self.ISpriteInstance {},
	Effectgameover: class extends self.ISpriteInstance {},
	ArmazenamentoLocal: class extends self.IInstance {},
	MouseOver: class extends self.ISpriteInstance {},
	ButtonsSound: class extends self.ISpriteInstance {}
}